- key: CSMR
  title: "European Conference on Software Maintenance and Reengineering"
- key: "ESE"
  title: "*Empirical Software Engineering*"
- key: "ESEC/FSE"
  title: "European Software Engineering Conference/Foundations of Software Engineering"
- key: "ESEM"
  title: "Empirical Software Engineering and Measurement"
- key: "FSE"
  title: "Foundations of Software Engineering"
- key: "ICPC"
  title: "International Conference on Program Comprehension"
- key: "ICSE"
  title: "International Conference on Software Engineering"
- key: "ICSM"
  title: "International Conference on Software Maintenance"
- key: "MSR"
  title: "International Conference on Mining Software Repositories"
- key: "OSDI"
  title: "Operating Systems Design and Implementation"
- key: "PLATEAU"
  title: "Workshop on Evaluation and Usability of Programming Languages and Tools"
- key: "PLoS Comp Bio"
  title: "PLoS Computational Biology"
- key: "PROMISE"
  title: "International Conference on Predictive Models in Software Engineering"
- key: "SANER"
  title: "Conference on Software Analysis, Evolution, and Reengineering"
- key: "SIGCSE"
  title: "ACM Technical Symposium on Computer Science Education"
- key: "SIGPLAN"
  title: "ACM SIGPLAN Notices"
- key: "TSE"
  title: "*IEEE Transactions on Software Engineering*"
- key: "WCRE"
  title: "Working Conference on Reverse Engineering"
