site_name: "McCole"
repo_url: https://github.com/gvwilson/mccole/
docs_dir: _docs
site_dir: docs

nav:
- Main:
  - Home Page: index.md
  - License: license.md
  - Code of Conduct: conduct.md
- Example:
  - Sample Book: sample/index.html
- Code:
  - Accounting: accounting.md
  - Bibliography: bib.md
  - Checks: check.md
  - File Collection: collect.md
  - Configuration: config.md
  - Cross References: crossref.md
  - Glossary: gloss.md
  - File Inclusion: include.md
  - Main Driver: mccole.md
  - Patterns: patterns.md
  - Render HTML: render.md
  - Preview Server: server.md
  - Show Standard Files: show.md
  - Template Expansion: template.md
  - Tokenize Markdown: tokenize.md
  - Utilities: util.md
  - Writing Files: write.md

plugins:
- search
- mkdocstrings

theme: readthedocs
